name: Build

on:
  push:
    branches:
      - develop
      - beta
      - master
  pull_request:

env:
  CI_TOOLS_VERSION: "3.3.1"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 14.x

      - name: Install ci_tools v${{ env.CI_TOOLS_VERSION }}
        run: sudo npm install --global @process-engine/ci_tools@${{ env.CI_TOOLS_VERSION }}

      - run: npm ci

      - name: Prepare version
        id: prepare_version
        run: |
          ci_tools prepare-version --allow-dirty-workdir
          echo "::set-output name=VERSION::$(ci_tools get-version)"
          echo "::set-output name=MAJOR_VERSION::$(ci_tools get-version --major)"

      - name: Publish npm
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ci_tools publish-npm-package --create-tag-from-branch-name

      - name: Commit & tag version
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GH_USER: ${{ secrets.GH_CI_USER_NAME }}
          GH_TOKEN: ${{ secrets.GH_CI_USER_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_CI_USER_EMAIL }}
        run: |
          git config user.email $GH_EMAIL
          git config user.name $GH_USER
          ci_tools commit-and-tag-version --only-on-primary-branches
          ci_tools update-github-release --only-on-primary-branches --use-title-and-text-from-git-tag
